import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

function inputTextBox(inputFieldName, value, onChange) {
    return (
        <div style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'column'
        }}>
            <label>{inputFieldName}</label><br />
            <textarea 
                value={value} 
                onChange={onChange} 
                type="text" 
            />
        </div>
    );
}

function selectValueBox(inputFieldName, options, value, onChange) {
    return (
        <div style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'column'
        }}>
            <label>{inputFieldName}</label><br />
            <select value={value} onChange={onChange}>
                {options.map((option) => (
                    <option key={option} value={option}>{option}</option>
                ))}
            </select>
        </div>
    );
}

function FilmoFormosLangas() {
    const [movie, setMovie] = useState("");
    const [startDate, setStartDate] = useState("");
    const [endDate, setEndDate] = useState("");
    const [coverImage, setCoverImage] = useState("");
    const [description, setDescription] = useState("");
    const [officialTrailerLink, setOfficialTrailerLink] = useState("");
    const [duration, setDuration] = useState(0);
    const [studio, setStudio] = useState("");
    const [isDubbed, setIsDubbed] = useState(false);
    const [hasSubtitles, setHasSubtitles] = useState(false);
    const [movieLanguage, setMovieLanguage] = useState(0); // id of selected language
    const [ageCensorship, setAgeCensorship] = useState(0); // id of selected censorship
    
    const [movieLanguageList, setMovieLanguageList] = useState([]);
    const [ageCensorshipList, setAgeCensorshipList] = useState([]);
    
    const getMovieLanguageList = async () => {
        const response = await axios.get('https://localhost:7241/GetAvailableMovieLanguageList');
        setMovieLanguageList(response.data);
    };

    const getAgeCensorshipList = async () => {
        const response = await axios.get('https://localhost:7241/GetMovieAgeCensorshipList');
        setAgeCensorshipList(response.data);
    };

    const handleSubmit = async () => {
        const movieData = {
            id: 0, // Assuming id is auto-generated by the database
            title: movie, // Ensure movie title is a string
            startingFrom: startDate, // Ensure this is in the correct format for the backend (YYYY-MM-DD)
            showingUntil: endDate, // Ensure this is in the correct format
            cover: coverImage, // Ensure cover image is a string (path or URL)
            isDubbed: isDubbed, // Boolean
            subtitles: hasSubtitles, // Boolean
            description: description, // String
            trailerLink: officialTrailerLink, // String (nullable)
            duration: parseInt(duration), // Ensure this is an integer
            studio: studio, // String
            language: movieLanguage, // Ensure this is an integer matching backend model
            ageCensorship: ageCensorship // Ensure this is an integer matching backend model
        };
    
        try {
            const response = await axios.post('https://localhost:7241/AddNewMovie', movieData);
            console.log('Movie saved successfully:', response.data);
        } catch (error) {
            console.error('Error saving movie:', error.response ? error.response.data : error);
        }
    };

    useEffect(() => {
        getMovieLanguageList();
        getAgeCensorshipList();
    }, []);

    return (
        <div style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'column'
        }}>
            <h1>Naujo filmo forma</h1>

            {inputTextBox("Filmo pavadinimas", movie, (e) => setMovie(e.target.value))}
            {inputTextBox("Pradedamas rodyti nuo", startDate, (e) => setStartDate(e.target.value))}
            {inputTextBox("Baigiamas rodyti iki", endDate, (e) => setEndDate(e.target.value))}
            {inputTextBox("Viršelio nuotraukos vieta (.jpg formato)", coverImage, (e) => setCoverImage(e.target.value))}
            {selectValueBox("Yra dubliuotas", ["Taip", "Ne"], isDubbed ? "Taip" : "Ne", (e) => setIsDubbed(e.target.value === "Taip"))}
            {selectValueBox("Turi subtitrus", ["Taip", "Ne"], hasSubtitles ? "Taip" : "Ne", (e) => setHasSubtitles(e.target.value === "Taip"))}
            {inputTextBox("Filmo aprašas", description, (e) => setDescription(e.target.value))}
            {inputTextBox("Nuoroda į oficialų anonsą", officialTrailerLink, (e) => setOfficialTrailerLink(e.target.value))}
            {inputTextBox("Trukmė sekundėmis", duration, (e) => setDuration(e.target.value))}
            {inputTextBox("Filmo studija", studio, (e) => setStudio(e.target.value))}
            {selectValueBox("Filmo kalba", movieLanguageList.map(e => e.name), movieLanguage, (e) => setMovieLanguage(parseInt(e.target.value)))}
            {selectValueBox("Amžiaus cenzas", ageCensorshipList.map(e => e.name), ageCensorship, (e) => setAgeCensorship(parseInt(e.target.value)))}

            <button onClick={handleSubmit}>Save Movie</button>
        </div>
    );
}

export default FilmoFormosLangas;
